### ISSUE TITLE
Feature - Hide Likes Count

### ISSUE THREAD

**Issue by taimurkashif02** [kgabriel113/ByteWalk#27]
I've decided to implement a new feature into ByteWalk - 'Hide Likes Count'. This feature essentially gives users the choice to hide the likes on posts. The users go into Update Profile and then select the toggle checkbox that will 'hide' the counts of likes everywhere the user sees posts.

**Comment by thryngabriel** [comment]
The schema migrations don't seem to be working after pulling these changes

**Comment by taimurkashif02** [comment]
Are you pulling from the correct branch? It's working for me.
